example/frontend/urls.py
from django.urls import path
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from . import views
from . import ajax_datatable_views

app_name = 'frontend'


urlpatterns = [
    path('', TemplateView.as_view(template_name="frontend/index.html"), name="index"),
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGIN_REDIRECT_URL), name='logout'),

    path('tracks/', views.tracks_list_view, name="tracks-list"),
    path('ajax_datatable/tracks/', ajax_datatable_views.TrackAjaxDatatableView.as_view(), name="ajax_datatable_track"),
    path('ajax_datatable/album/', ajax_datatable_views.AlbumAjaxDatatableView.as_view(), name="ajax_datatable_album"),
    path('ajax_datatable/artist/',
         ajax_datatable_views.ArtistAjaxDatatableView.as_view(), name="ajax_datatable_artist"),

    path('ajax_datatable/permissions/', ajax_datatable_views.PermissionAjaxDatatableView.as_view(),
         name="ajax_datatable_permissions"),
    path('minimal/', TemplateView.as_view(template_name='frontend/minimal.html'), name="minimal"),

    path('custompks/', TemplateView.as_view(template_name='frontend/custompk/list.html'), name="custompks-list"),
    path('ajax_datatable/custompks/',
         ajax_datatable_views.CustomPkAjaxDatatableView.as_view(), name="ajax_datatable_custompk"),

    path('side_filters/', TemplateView.as_view(template_name='frontend/side_filters.html'), name="side_filters"),
]

example/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', lambda x: redirect('/tracks/'), name='index'),
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
] \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/backend/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import PermissionDenied
from ajax_datatable.utils import format_datetime


class Tag(models.Model):
    name = models.CharField(null=False, blank=False, max_length=256)

    def __str__(self):
        return self.name


TAG2_CHOICES = (
    ('rock', 'Rock'),
    ('pop', 'Pop'),
    ('new-age', 'New Age'),
)


class Tag2(models.Model):
    name = models.CharField(null=False, blank=False, max_length=256, choices=TAG2_CHOICES)

    def __str__(self):
        return self.name


################################################################################
# BaseModel

class BaseModel(models.Model):
    """
    Base class for all models;
    defines common metadata
    """
    class Meta:
        abstract = True
        ordering = ('-created', )  # better choice for UI
        get_latest_by = "-created"

    # Primary key
    id = models.UUIDField('id', default=uuid.uuid4, primary_key=True, unique=True,
                          null=False, blank=False, editable=False)
    name = models.CharField(null=False, blank=False, max_length=256)
    url = models.CharField(null=False, blank=True, max_length=256)

    # metadata
    created = models.DateTimeField(_('created'), null=True, blank=True, )
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_(
        'created by'), null=True, blank=True, related_name='+', on_delete=models.SET_NULL)
    updated = models.DateTimeField(_('updated'), null=True, blank=True, )
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_(
        'updated by'), null=True, blank=True, related_name='+', on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.name)

    def get_admin_url(self):
        return reverse("admin:%s_%s_change" %
                       (self._meta.app_label, self._meta.model_name), args=(self.id,))

    def get_absolute_url(self):
        return self.get_admin_url()

    def created_display(self):
        return format_datetime(self.created)
    created_display.short_description = _('Created')
    created_display.admin_order_field = 'created'

    def updated_display(self):
        return format_datetime(self.updated)
    updated_display.short_description = _('Updated')
    updated_display.admin_order_field = 'updated'

    def save(self, *args, **kwargs):
        today = timezone.now()
        if self.created is None:
            self.created = today
        self.updated = today
        return super(BaseModel, self).save(*args, **kwargs)


class Artist(BaseModel):

    notes = models.TextField(null=False, blank=True)

    class Meta(BaseModel.Meta):
        abstract = False


class Album(BaseModel):

    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, null=False, blank=False)
    year = models.IntegerField(null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)

    class Meta(BaseModel.Meta):
        abstract = False
        get_latest_by = "-release_date"


class Track(BaseModel):

    album = models.ForeignKey(Album, on_delete=models.CASCADE, null=False, blank=False)
    position = models.IntegerField(default=0, null=False, blank=False)
    tags = models.ManyToManyField(Tag, blank=True)
    tags2 = models.ManyToManyField(Tag2, verbose_name="tags w/choices", blank=True)

    class Meta(BaseModel.Meta):
        abstract = False
        ordering = ['position', ]

    def clone(self, request=None):

        if request and not request.user.has_perm('backend.add_song'):
            raise PermissionDenied

        obj = Track.objects.get(id=self.id)
        obj.pk = uuid.uuid4()
        # TODO: this seems abandoned, Track has no field description and there is
        # no function increment_revision
        # obj.description = increment_revision(self.description)
        obj.save()
        return obj


################################################################################

class CustomPk(models.Model):

    # Primary key
    auto_increment_id = models.AutoField(primary_key=True)
    name = models.CharField(null=False, blank=False, max_length=256)

example/frontend/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from project.query_debugger import query_debugger
# from backend.models import Track


User = get_user_model()


@query_debugger
def tracks_list_view(request):
    """
    Render the page which contains the table.
    That will in turn invoke (via Ajax) object_datatable_view(), to fill the table content
    """
    # model = Track
    template_name = "frontend/track/list.html"

    return render(request, template_name, {
        # 'model': model,
    })

example/frontend/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}
{% block body-class %}login{% endblock %}

{% block content %}

    <form method="post">
        <h2>Please sign in</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <div class="submit-row">
            <button class="btn btn-lg btn-primary" type="submit">Login</button>
        </div>
    </form>

{% endblock %}

example/frontend/templates/base.html
{% load i18n static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='stylesheet' href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel='stylesheet' href="{% static 'font-awesome/css/font-awesome.min.css' %}">

    <link href="{% static 'ajax_datatable/css/style.css' %}" rel="stylesheet" />
    <link rel='stylesheet' href="{% static 'datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel='stylesheet' href="{% static 'datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" />

    <link rel="stylesheet" href="{% static 'frontend/css/frontend.css' %}">
    {% block extrastyle %}
    {% endblock extrastyle %}
</head>

<body class="page-{% block body-class%}{% endblock body-class%}">

    <a href="https://github.com/morlandi/django-ajax-datatable" style="float: right">
        <img loading="lazy" width="149" height="149"
        src="{% static 'frontend/images/forkme_right_darkblue_121621.png' %}"
        class="attachment-full size-full"
        alt="Fork me on GitHub"
        data-recalc-dims="1">
    </a>

    {% include 'navbar.html' %}

    <main role="main" class="container">

        <div id="page-title"><h2>{% block page-title %}{% endblock page-title %}</h2></div>

        {% block messages %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{message.tag}}">{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        {% endblock messages %}

        <div id="content">
        {% block content %}
            <h1>Content goes here</h1>
        {% endblock content %}
        </div>

    </main>

    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'ajax_datatable/js/utils.js' %}"></script>

    <script src="{% static 'datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>

    <script src="{% static 'datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>

    <script src="{% static 'jszip/dist/jszip.min.js' %}"></script>
    <script src="{% static 'pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'pdfmake/build/vfs_fonts.js' %}"></script>

    <script>

    </script>

    {% block extrajs %}
    {% endblock extrajs %}

</body>

</html>

example/frontend/templates/frontend/custompk/list.html
{% extends 'base.html' %}
{% load i18n %}

{% block page-title %}{% trans 'CustomPK table content' %}{% endblock page-title %}


{% block content %}

    <p>
    Managing a table with a PK named "auto_increment_id"
    </p>

    <div class="table-responsive">
        <table id="datatable" width="100%" class="table table-striped table-bordered dt-responsive compact nowrap">
        </table>
    </div>

{% endblock content %}


{% block extrajs %}

    {{ block.super }}
    <script language="javascript">

        $( document ).ready(function() {
            AjaxDatatableViewUtils.initialize_table(
                $('#datatable'),
                "{% url 'frontend:ajax_datatable_custompk' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: true,
                    scrollX: false
                }, {
                    // extra_data
                    // ...
                },
                );
        });

    </script>
{% endblock %}

example/frontend/templates/frontend/index.html
{% extends 'base.html' %}

{% block page-title %}Index{% endblock page-title %}
{% block body-class%}index{% endblock body-class %}


{% block content %}

<h1>hello</h1>

{% endblock content %}

example/frontend/templates/frontend/minimal.html
{% extends 'base.html' %}
{% load i18n %}

{% block page-title %}{% trans 'A minimal example' %}{% endblock page-title %}

{% block extrastyle %}
    <style>
        pre { font-size: 11px; font-family: monospace; background-color: #fff; padding: 10px 0 0 10px;}
    </style>
{% endblock extrastyle %}


{% block content %}

    <p>
    A minimal example using AjaxDatatableView.
    </p>

    <h3>How it works</h3>

    <p>An AjaxDatatableView-derived view describes the desired table content and behaviour as follows:</p>

    <pre>
from ajax_datatable.views import AjaxDatatableView
from django.contrib.auth.models import Permission

class PermissionAjaxDatatableView(AjaxDatatableView):

    model = Permission
    title = 'Permissions'
    initial_order = [["app_label", "asc"], ]
    length_menu = [[10, 20, 50, 100, -1], [10, 20, 50, 100, 'all']]
    search_values_separator = '+'

    column_defs = [
         AjaxDatatableView.render_row_tools_column_def(),
        {'name': 'id', 'visible': False, },
        {'name': 'codename', 'visible': True, },
        {'name': 'name', 'visible': True, },
        {'name': 'app_label', 'foreign_field': 'content_type__app_label', 'visible': True, },
        {'name': 'model', 'foreign_field': 'content_type__model', 'visible': True, },
    ]
    </pre>

    <p>and is referenced in the template like so:</p>

    <pre>
&lt;div class="table-responsive"&gt;
    &lt;table id="datatable" width="100%" class="table table-striped table-bordered dt-responsive compact nowrap"&gt;
    &lt;/table&gt;
&lt;/div&gt;

&lt;script language="javascript"&gt;

    $( document ).ready(function() {
        AjaxDatatableViewUtils.initialize_table(
            $('#datatable'),
            "{% url 'frontend:ajax_datatable_permissions' %}",
            {
                // extra_options (example)
                processing: false,
                autoWidth: false,
                full_row_select: true,
                scrollX: false
            }, {
                // extra_data
                // ...
            },
            );
    });

&lt;/script&gt;
    </pre>

    <p>where "/ajax_datatable_permissions/" is the endpoint to the previous view:</p>

    <pre>
urlpatterns = [
    ...
    path('ajax_datatable/permissions/', ajax_datatable_views.PermissionAjaxDatatableView.as_view(), name="ajax_datatable_permissions"),
    ...
]
    </pre>

    <div class="table-responsive">
        <table id="datatable" width="100%" class="table table-striped table-bordered dt-responsive compact nowrap">
        </table>
    </div>

{% endblock content %}


{% block extrajs %}

    {{ block.super }}
    <script language="javascript">

        $( document ).ready(function() {
            AjaxDatatableViewUtils.initialize_table(
                $('#datatable'),
                "{% url 'frontend:ajax_datatable_permissions' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: true,
                    scrollX: false
                }, {
                    // extra_data
                    // ...
                },
                );
        });

    </script>
{% endblock %}

example/frontend/templates/frontend/minimal/list.html
{% extends 'base.html' %}
{% load i18n %}

{% block page-title %}{% trans 'A minimal example' %}{% endblock page-title %}

{% block extrastyle %}
    <style>
        pre { font-size: 11px; font-family: monospace; background-color: #fff; padding: 10px 0 0 10px;}
    </style>
{% endblock extrastyle %}


{% block content %}

    <p>
    A minimal example using AjaxDatatableView.
    </p>

    <div class="table-responsive">
        <table id="datatable" width="100%" class="table table-striped table-bordered dt-responsive compact nowrap">
        </table>
    </div>

    <h3>How it works</h3>

    <p>An AjaxDatatableView-derived view describes the desired table content and behaviour as follows:</p>

    <pre>
from ajax_datatable.views import AjaxDatatableView
from django.contrib.auth.models import Permission

class PermissionAjaxDatatableView(AjaxDatatableView):

    model = Permission
    title = 'Permissions'
    initial_order = [["app_label", "asc"], ]
    length_menu = [[10, 20, 50, 100, -1], [10, 20, 50, 100, 'all']]
    search_values_separator = '+'

    column_defs = [
         AjaxDatatableView.render_row_tools_column_def(),
        {'name': 'id', 'visible': False, },
        {'name': 'codename', 'visible': True, },
        {'name': 'name', 'visible': True, },
        {'name': 'app_label', 'foreign_field': 'content_type__app_label', 'visible': True, },
        {'name': 'model', 'foreign_field': 'content_type__model', 'visible': True, },
    ]
    </pre>

    <p>and is referenced in the template like so:</p>

    <pre>
&lt;div class="table-responsive"&gt;
    &lt;table id="datatable" width="100%" class="table table-striped table-bordered dt-responsive compact nowrap"&gt;
    &lt;/table&gt;
&lt;/div&gt;

&lt;script language="javascript"&gt;

    $( document ).ready(function() {
        AjaxDatatableViewUtils.initialize_table(
            $('#datatable'),
            "{% url 'frontend:ajax_datatable_permissions' %}",
            {
                // extra_options (example)
                processing: false,
                autoWidth: false,
                full_row_select: true,
                scrollX: false
            }, {
                // extra_data
                // ...
            },
            );
    });

&lt;/script&gt;
    </pre>

    <p>where "/ajax_datatable_permissions/" is the endpoint to the previous view:</p>

    <pre>
urlpatterns = [
    ...
    path('ajax_datatable/permissions/', ajax_datatable_views.PermissionAjaxDatatableView.as_view(), name="ajax_datatable_permissions"),
    ...
]
    </pre>

{% endblock content %}


{% block extrajs %}

    {{ block.super }}
    <script language="javascript">

        $( document ).ready(function() {
            AjaxDatatableViewUtils.initialize_table(
                $('#datatable'),
                "{% url 'frontend:ajax_datatable_permissions' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: true,
                    scrollX: false
                }, {
                    // extra_data
                    // ...
                },
                );
        });

    </script>
{% endblock %}

example/frontend/templates/frontend/side_filters.html
{% extends 'base.html' %}
{% load i18n %}

{% block page-title %}{% trans 'Side filters' %}{% endblock page-title %}

{% block extrastyle %}
    <style>
        pre { font-size: 11px; font-family: monospace; background-color: #fff; padding: 10px 0 0 10px;}
        input[type="number"] { width: 100px; }
        .filters {
            border: 1px solid #999;
            padding-top: 10px;
        }
    </style>
{% endblock extrastyle %}


{% block content %}

    <p>Example with Side filters</p>

    <p>
    Sometimes you need to provide to the user more control over the queryset
    used to populate the table, using interactive and specific filters.
    </p>

    <p>
    In those cases, you can easily add a sidebar with the required widgets,
    then collect and apply user selections at every table refresh.
    </p>

    <h3>How it works</h3>

    <p>
        First, add to the template all required input widgets, and schedule a table redraw
        whenever a filter has been changed (or when you believe is more appropriate)
    </p>

    <pre>
&lt;div class="col-sm-2 filters"&gt;
    &lt;h4&gt;Filters&lt;/h4&gt;
    &lt;label for="from_year"&gt;From year:&lt;/label&gt;&lt;input type="number" id="from_year"&gt;
    &lt;label for="to_year"&gt;To year:&lt;/label&gt;&lt;input type="number" id="to_year"&gt;
    ...
    </pre>

    <pre>
$(document).ready(function() {

    $('.filters input').on('change paste keyup', function() {
        // redraw the table
        $('#datatable').DataTable().ajax.reload(null, false);
    });

});
    </pre>

    <p>
    At table initialization, register in the "extra data" section the callbacks needed
    to collect user selections
    </p>

    <pre>
$(document).ready(function() {

    AjaxDatatableViewUtils.initialize_table(
        ...
        }, {
            // extra_data
            from_year: function() { return $('input#from_year').val() },
            to_year: function() { return $('input#to_year').val() },
            check_year_null: function() { return $("input[name='check_year_null']:checked").val() }
        },
    );

});
    </pre>

    <p>
        Those "extra data" values will be sent to the AjaxDatatableView with
        every request; you can take advantage of those by filtering the queryset
        in the `get_initial_queryset()` override.
    </p>

    <pre>
class AlbumAjaxDatatableView(AjaxDatatableView):

    ...

    def get_initial_queryset(self, request=None):

        def get_numeric_param(key):
            try:
                value = int(request.POST.get(key))
            except:
                value = None
            return value

        queryset = super().get_initial_queryset(request=request)

        check_year_null = get_numeric_param('check_year_null')
        if check_year_null is not None:
            if check_year_null == 0:
                queryset = queryset.filter(year=None)
            elif check_year_null == 1:
                queryset = queryset.exclude(year=None)

        from_year = get_numeric_param('from_year')
        if from_year is not None:
            queryset = queryset.filter(year__gte=from_year)

        to_year = get_numeric_param('to_year')
        if to_year is not None:
            queryset = queryset.filter(year__lte=to_year)

        return queryset
    </pre>

    <div class="container">
        <div class="row">
            <div class="col-sm-2 filters">
                <h4>Filters</h4>
                <label for="from_year">From year:</label><input type="number" id="from_year">
                <label for="to_year">To year:</label><input type="number" id="to_year">
                <br />
                <br />
                <label>Provided:</label><br />
                <input type="radio" id="year_null" name="check_year_null" value="0">
                <label for="year_null">year is NULL</label><br>
                <input type="radio" id="year_not_null" name="check_year_null" value="1">
                <label for="year_not_null">year is not NULL</label><br>
                <input type="radio" id="year_any" name="check_year_null" value="-1">
                <label for="year_any">any</label>
            </div>
            <div class="col-sm-10">
                <div class="table-responsive">
                    <table id="datatable" width="100%" class="table table-striped table-bordered dt-responsive compact nowrap">
                    </table>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}


{% block extrajs %}

    {{ block.super }}
    <script language="javascript">

        $(document).ready(function() {

            AjaxDatatableViewUtils.initialize_table(
                $('#datatable'),
                "{% url 'frontend:ajax_datatable_album' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: true,
                    scrollX: false
                }, {
                    // extra_data
                    // ...
                    from_year: function() { return $('input#from_year').val() },
                    to_year: function() { return $('input#to_year').val() },
                    check_year_null: function() { return $("input[name='check_year_null']:checked").val() }
                },
            );

            $('.filters input').on('change paste keyup', function() {
                // redraw the table
                $('#datatable').DataTable().ajax.reload(null, false);
            });
        });

    </script>
{% endblock %}

example/frontend/templates/frontend/track/list.html
{% extends 'base.html' %}
{% load i18n %}

{% block page-title %}{% trans 'List Tracks' %}{% endblock page-title %}


{% block extrastyle %}
    <style>
        .btn-edit { font-size: 10px; padding: 2px 8px; }
    </style>
{% endblock extrastyle %}


{% block content %}

    <p>
    This tables show data collected from three 1-N related models: Track, Album and Artist
    </p>

    <h3>Tracks</h3>

    <div class="table-responsive">
        <table id="datatable-track" width="100%" class="table table-striped table-bordered dt-responsive compact nowrap">
        </table>
    </div>

    <h3>Albums</h3>

    <div class="table-responsive">
        <table id="datatable-album" width="100%" class="table table-striped table-bordered dt-responsive compact nowrap">
        </table>
    </div>

    <h3>Artists</h3>

    <div class="table-responsive">
        <table id="datatable-artist" width="100%" class="table table-striped table-bordered dt-responsive compact nowrap">
        </table>
    </div>

{% endblock content %}


{% block extrajs %}

    {{ block.super }}
    <script language="javascript">

        $( document ).ready(function() {

            AjaxDatatableViewUtils.initialize_table(
                $('#datatable-track'),
                "{% url 'frontend:ajax_datatable_track' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: false,
                    scrollX: false
                }, {
                    // extra_data
                    // ...
                },
            );

            AjaxDatatableViewUtils.initialize_table(
                $('#datatable-album'),
                "{% url 'frontend:ajax_datatable_album' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: false,
                    scrollX: false
                }, {
                    // extra_data
                    // ...
                },
            );

            AjaxDatatableViewUtils.initialize_table(
                $('#datatable-artist'),
                "{% url 'frontend:ajax_datatable_artist' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: false,
                    scrollX: false
                }, {
                    // extra_data
                    // ...
                },
            );
        });

    </script>
{% endblock %}

example/frontend/templates/navbar.html
{% load i18n %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="/">django-ajax-datatable example</a>
    {% if PROJECT_BUILD %}<small style="color: #ccc;">({{PROJECT_BUILD}})</small>{% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">

            {% comment %}
            <li class="nav-item">
                <a class="nav-link page-index" href="{% url 'frontend:tracks-list' %}">{% trans 'List tracks' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link page-index" href="{% url 'frontend:custompks-list' %}">{% trans 'CustomPK' %}</a>
            </li>
            {% endcomment %}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Examples</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'frontend:index' %}">List tracks</a>
                    <a class="dropdown-item" href="{% url 'frontend:minimal' %}">Minimal example</a>
                    <a class="dropdown-item" href="{% url 'frontend:custompks-list' %}">Custom PK</a>
                    <a class="dropdown-item" href="{% url 'frontend:side_filters' %}">Side filters</a>
                </div>
            </li>

            {% comment %}
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
            {% endcomment %}

            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hello, {{request.user}}</a>
                <div class="dropdown-menu" aria-labelledby="dropdown02">
                    {% if request.user.is_staff %}
                        <a class="dropdown-item" href="/admin/">admin</a>
                    {% endif %}
                    <a class="dropdown-item" href="{% url 'frontend:logout' %}">Logout</a>
                </div>
            </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'frontend:login' %}" tabindex="-1" aria-disabled="false">Login</a>
                </li>
            {% endif %}
        </ul>
        {% comment %}
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% endcomment %}
    </div>
</nav>